-- Supabase schema for Tất tần tật - Phú Tân
-- Run in Supabase SQL editor. This creates content, vlog, newsletter, and community help tables.

create extension if not exists pgcrypto;

create table if not exists public.site_settings (
  row_key text primary key,
  value jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.content_sections (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  description text,
  route text not null,
  display_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.content_items (
  id uuid primary key default gen_random_uuid(),
  legacy_id int,
  section_slug text not null references public.content_sections(slug) on update cascade on delete restrict,
  title text not null,
  excerpt text,
  description text,
  content text,
  image_url text,
  category text,
  address text,
  rating numeric(2,1),
  severity text,
  published_date date,
  route text,
  metadata jsonb not null default '{}'::jsonb,
  display_order int not null default 0,
  is_featured boolean not null default false,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(section_slug, legacy_id)
);

create index if not exists content_items_section_order_idx
  on public.content_items(section_slug, is_published, display_order, published_date desc, created_at desc);

create table if not exists public.vlog_reviews (
  id uuid primary key default gen_random_uuid(),
  legacy_id int unique,
  news_legacy_id int,
  content_item_id uuid references public.content_items(id) on delete set null,
  title text not null,
  subtitle text,
  video_url text not null,
  poster_url text,
  host text,
  duration_label text,
  likes_count int not null default 0,
  display_order int not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vlog_locations (
  id uuid primary key default gen_random_uuid(),
  vlog_review_id uuid not null references public.vlog_reviews(id) on delete cascade,
  time_seconds int not null check (time_seconds >= 0),
  name text not null,
  note text,
  image_url text,
  latitude numeric(10,7),
  longitude numeric(10,7),
  display_order int not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists vlog_locations_review_time_idx
  on public.vlog_locations(vlog_review_id, time_seconds);

create table if not exists public.newsletter_subscribers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  source text not null default 'homepage',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  title text not null,
  urgency text not null check (urgency in ('urgent', 'medium', 'normal')),
  category text not null,
  description text not null,
  location text not null,
  latitude numeric(10,7),
  longitude numeric(10,7),
  contact_name text not null,
  contact_phone text not null,
  images text[] not null default '{}',
  status text not null default 'pending' check (status in ('pending', 'in_progress', 'completed', 'closed')),
  volunteers_count int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists requests_status_urgency_idx
  on public.requests(status, urgency, created_at desc);

create table if not exists public.volunteers (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.requests(id) on delete cascade,
  name text not null,
  phone text not null,
  support_type text not null check (support_type in ('money', 'labor', 'time', 'goods')),
  description text not null,
  created_at timestamptz not null default now()
);

create index if not exists volunteers_request_id_idx on public.volunteers(request_id);

create table if not exists public.admin_settings (
  row_key text primary key,
  value text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_site_settings_updated_at on public.site_settings;
create trigger set_site_settings_updated_at before update on public.site_settings
for each row execute function public.set_updated_at();

drop trigger if exists set_content_sections_updated_at on public.content_sections;
create trigger set_content_sections_updated_at before update on public.content_sections
for each row execute function public.set_updated_at();

drop trigger if exists set_content_items_updated_at on public.content_items;
create trigger set_content_items_updated_at before update on public.content_items
for each row execute function public.set_updated_at();

drop trigger if exists set_vlog_reviews_updated_at on public.vlog_reviews;
create trigger set_vlog_reviews_updated_at before update on public.vlog_reviews
for each row execute function public.set_updated_at();

drop trigger if exists set_requests_updated_at on public.requests;
create trigger set_requests_updated_at before update on public.requests
for each row execute function public.set_updated_at();

create or replace function public.increment_request_volunteers()
returns trigger
language plpgsql
as $$
begin
  update public.requests
  set volunteers_count = volunteers_count + 1
  where id = new.request_id;
  return new;
end;
$$;

drop trigger if exists increment_request_volunteers_after_insert on public.volunteers;
create trigger increment_request_volunteers_after_insert
after insert on public.volunteers
for each row execute function public.increment_request_volunteers();

alter table public.site_settings enable row level security;
alter table public.content_sections enable row level security;
alter table public.content_items enable row level security;
alter table public.vlog_reviews enable row level security;
alter table public.vlog_locations enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.requests enable row level security;
alter table public.volunteers enable row level security;
alter table public.admin_settings enable row level security;

drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings" on public.site_settings for select using (true);

drop policy if exists "Public can read active sections" on public.content_sections;
create policy "Public can read active sections" on public.content_sections for select using (is_active = true);

drop policy if exists "Public can read published content" on public.content_items;
create policy "Public can read published content" on public.content_items for select using (is_published = true);

drop policy if exists "Public can read published vlogs" on public.vlog_reviews;
create policy "Public can read published vlogs" on public.vlog_reviews for select using (is_published = true);

drop policy if exists "Public can read vlog locations" on public.vlog_locations;
create policy "Public can read vlog locations" on public.vlog_locations for select using (true);

drop policy if exists "Public can subscribe newsletter" on public.newsletter_subscribers;
create policy "Public can subscribe newsletter" on public.newsletter_subscribers for insert with check (true);

drop policy if exists "Public can read requests" on public.requests;
create policy "Public can read requests" on public.requests for select using (true);

drop policy if exists "Public can create requests" on public.requests;
create policy "Public can create requests" on public.requests for insert with check (true);

drop policy if exists "Public can update request images" on public.requests;
create policy "Public can update request images" on public.requests for update using (true) with check (true);

drop policy if exists "Public can read volunteers" on public.volunteers;
create policy "Public can read volunteers" on public.volunteers for select using (true);

drop policy if exists "Public can create volunteers" on public.volunteers;
create policy "Public can create volunteers" on public.volunteers for insert with check (true);

drop policy if exists "Public can read admin setting values" on public.admin_settings;
create policy "Public can read admin setting values" on public.admin_settings for select using (true);

insert into storage.buckets (id, name, public)
values ('request-photos', 'request-photos', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public can upload request photos" on storage.objects;
create policy "Public can upload request photos" on storage.objects
for insert with check (bucket_id = 'request-photos');

drop policy if exists "Public can read request photos" on storage.objects;
create policy "Public can read request photos" on storage.objects
for select using (bucket_id = 'request-photos');

drop policy if exists "Public can delete request photos" on storage.objects;
create policy "Public can delete request photos" on storage.objects
for delete using (bucket_id = 'request-photos');
